<?php
/*******************************************
 *
 * 2014 - Programación Web
 * Grado en Ingeniería Informática
 *
 * Ernesto Serrano <info@ernesto.es>
 * 
 *
 *******************************************
 *
 * Créditos de la página 
 *
 ******************************************************************************/
?>

<br />

<div class="container">

<h2><?php echo $page_title; ?></h2>

<br />

<p><strong><?php echo SITE_NAME; ?></strong> is developed for the course of <strong>Programación Web</strong> at the <a href="http://www.ugr.es" target="_blank"><abbr title="University of Granada">UGR</abbr></a> by the students:</p>
	<ul>
		<li>Ernesto Serrano &lt;<a href="mailto:info@ernesto.es">info@ernesto.es</a>&gt;</li>
	</ul>
<br />
<p><strong><?php echo SITE_NAME; ?></strong> is developed using the next technologies, frameworks and libraries:</p>
<div class="row">
  <div class="col-md-4">
	<h3>Technologies</h3>
	<ul>
	<li>HTML5</li>
	<li>CSS3</li>
	<li>Javascript 1.3</li>
	<li>JSON</li>
	<li>PHP 5.4</li>
	<li>MySQL 5.5</li>
	</ul>


	<h3>Frameworks</h3>
	<ul>
	<li>Twitter Bootrsap</li>
	</ul>


	<h3>Libraries</h3>
	<ul>
	<li>Highchart.js</li>
	<li>Bootbox.js</li>
	<li>Validator.js</li>
	</ul>


  </div>
  <div class="col-md-8">

  	<img src="img/icon_mobile.png" alt="Trivial Mobile logo" />

  </div>
</div>








</div>



