<?php
/*******************************************
 *
 * 2014 - Programación Web
 * Grado en Ingeniería Informática
 *
 * Ernesto Serrano <info@ernesto.es>
 * 
 *
 *******************************************
 *
 *  Encabezado de la página, es comun para todas
 *
 ******************************************************************************/
?>
<?php
	// Nos guardamos cuando empieza la ejecución para saber cuanto
	// se tarda en procesar la página
	$start = microtime(true); 
?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" >
		<title><?php echo($page_title); ?> - <?php echo(SITE_NAME); ?></title>
		<meta name="description" content="<?php echo(SITE_NAME); ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="shortcut icon" type="image/x-icon" href="favicon.ico">

		<link rel="stylesheet" href="css/bootstrap.min.css">
		<style>
			body {
				padding-top: 50px;
				padding-bottom: 20px;
			}
		</style>
		<link rel="stylesheet" href="css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="css/main.css">
			
		<!-- bsie css patch -->
		  <!--[if lte IE 6]>
		  
		  <link rel="stylesheet" type="text/css" href="css/bootstrap-ie6.css">
		  <link rel="stylesheet" type="text/css" href="css/ie.css">
		  <![endif]-->

		<!--[if lt IE 8]>
			<link href="css/bootstrap-ie7.css" rel="stylesheet">
		<![endif]-->
		<script src="js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>

		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.0.min.js"><\/script>')</script>

        <script src="js/vendor/highcharts.js"></script>


	</head>
	<body>
		<!--[if lt IE 7]>
			<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
		<![endif]-->



	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	  <div class="container">
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		  <a class="navbar-brand" href="index.php?page=home"><?php echo SITE_NAME; ?></a>
	  </div><!--/.navbar-header -->

		  
		<?php if (isset($_SESSION['sess_email'])): ?>

		<div class="navbar-collapse collapse">
		  <ul class="nav navbar-nav">
			<li<?php if ($page == "home") echo " class=\"active\"";?>><a href="index.php?page=home">Home</a></li>
	  		<li<?php if ($page == "questions") echo " class=\"active\"";?>><a href="index.php?page=questions">Questions</a></li>

	  		<?php if ($_SESSION["sess_role"] == 1): ?>
	  			<!-- Estas opciones solo puden hacerlas los usuarios con rol de admin -->
				<li<?php if ($page == "categories") echo " class=\"active\"";?>><a href="index.php?page=categories">Categories</a></li>
				<li<?php if ($page == "languages") echo " class=\"active\"";?>><a href="index.php?page=languages">Languages</a></li>
				<li<?php if ($page == "users") echo " class=\"active\"";?>><a href="index.php?page=users">Users</a></li>
			<?php endif; ?>

			<li class="dropdown">
			  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tools <b class="caret"></b></a>
			  <ul class="dropdown-menu">
				<li><a href="index.php?page=info"><span class="glyphicon glyphicon-info-sign"></span> Server Info</a></li>
				<?php if ($_SESSION["sess_role"] == 1): ?>
		  			<!-- Estas opciones solo puden hacerlas los usuarios con rol de admin -->
					<li><a href="index.php?page=backup"><span class="glyphicon glyphicon-floppy-disk"></span> Backup</a></li>
				<?php endif; ?>
				<li class="divider"></li>
				<li class="dropdown-header">API</li>
				<li><a href="index.php?page=insert_question_demo">Suggest question</a></li>
				<li><a href="index.php?page=insert_correction_demo">Suggest correction</a></li>

				<?php if ($_SESSION["sess_role"] == 1): ?>
		  			<!-- Estas opciones solo puden hacerlas los usuarios con rol de admin -->
					<li class="dropdown-header">Export</li>
					<li><a href="export/export_csv.php" target="_blank">Export as CSV</a></li>
					<li><a href="export/export_java.php" target="_blank">Export as Java</a></li>
					<li><a href="export/export_js.php" target="_blank">Export as JavaScript</a></li>
				<?php endif; ?>
				<li class="divider"></li>
				<li><a href="index.php?page=statistics"><span class="glyphicon glyphicon-stats"></span> Statistics</a></li>
			  </ul>
			</li>
		  </ul>

				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, <?php echo $_SESSION['sess_name']; ?> <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="index.php?page=profile"><span class="glyphicon glyphicon-cog"></span> Profile</a></li>
							<li><a href="index.php?page=support"><span class="glyphicon glyphicon-envelope"> </span> Contact Support</a></li>
							<li class="divider"></li>
							<li><a href="logout.php"><span class="glyphicon glyphicon-off"></span> Logout</a></li>
						</ul>
					</li>
				</ul>


   
		</div><!--/.nav-collapse -->


		<?php endif; ?>

	</div>
</div>