<?php
/*******************************************
 *
 * 2014 - Programación Web
 * Grado en Ingeniería Informática
 *
 * Ernesto Serrano <erseco@correo.ugr.es>
 * 
 *
 *******************************************
 *
 *  Pagina home, esta la que se ve despues de iniciar sesión 
 *
 ******************************************************************************/
?>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1><?php echo SITE_NAME ?></h1>
        <p>Congratulations, if you can read this is because you are a translator of the many Atomik Soft trivia games, please, ride in the categories to start your work. If you need more info, please click on the Learn more button, thanks!</p>
        <p><a class="btn btn-primary btn-lg" role="button" href="index.php?page=credits">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <img class="img-square" alt="140x140" src="img/icon_mobile.png" style="width: 140px; height: 140px;">
          <h2>Trivial Mobile</h2>
          <p>Simple trivia question game, ideal for entertaining while you exercise the brain. </p>
          <p><a class="btn btn-default" href="https://play.google.com/store/apps/details?id=erseco.soft" role="button" target="_blank">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <img class="img-square" alt="140x140" src="img/icon_geek.png" style="width: 140px; height: 140px;">

          <h2>Geek Trivia</h2>
          <p>This geek trivia has came for the hardest players. A huge set of questions to swim into the real occidental culture. Cinema, cartoons, series, music, comic,...</p>
          <p><a class="btn btn-default" href="https://play.google.com/store/apps/details?id=erseco.soft.friki.trivial.landon" role="button" target="_blank">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <img class="img-square" alt="140x140" src="img/icon_rock.png" style="width: 140px; height: 140px;">
          <h2>Rock Trivia</h2>

          <p>Rock Trivia is available in english and spanish, you can change the language of the questions at any time to learn other languages. There's no excuse for hours of fun!</p>
          <p><a class="btn btn-default" href="https://play.google.com/store/apps/details?id=erseco.soft.trivial.mobile.rock" role="button" target="_blank">View details &raquo;</a></p>
        </div>
      </div>
    </div> <!-- /container -->   