<?php
/*******************************************
 *
 * 2014 - Programación Web
 * Grado en Ingeniería Informática
 *
 * Ernesto Serrano <erseco@correo.ugr.es>
 * 
 *
 *******************************************
 *
 * Muestra un formulario para poder enviar un mensaje de soporte, si se ha enviado
 * muestra un mensaje de agradecimiento
 *
 ******************************************************************************/
?>
<div class="container">
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well well-sm">

<?php
if (empty($_POST)):
?>


          <form class="form-horizontal" action="" method="post">
          <fieldset>
            <legend class="text-center">Contact us</legend>
    
            <!-- Asunto input-->
            <div class="form-group">
              <label class="col-md-3 control-label" for="name">Subject</label>
              <div class="col-md-9">
                <input id="subject" name="subject" type="text" placeholder="Enter subject" class="form-control">
              </div>
            </div>
    
            <!-- Message body -->
            <div class="form-group">
              <label class="col-md-3 control-label" for="message">Your message</label>
              <div class="col-md-9">
                <textarea class="form-control" id="message" name="message" placeholder="Please enter your message here..." rows="5"></textarea>
              </div>
            </div>
    
            <!-- Form actions -->
            <div class="form-group">
              <div class="col-md-12 text-right">
                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
              </div>
            </div>
          </fieldset>
          </form>
      
<?php
else:
	// Llamamos al fichero del controlador que envía el email y mostramos el mensaje de gracias
	include "controller/support.php";
?>
<h3>Thank for contact us, shortly our enginners will contact you</h3>
<?php
endif
?>

		</div>
      </div>
	</div>
</div>

